### ISSUE TITLE
Game start

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Chess-WRIO-Game#11]
Game start отображать через https://github.com/webRunes/Titter-WRIO-App, т.е. в виде картинки. Текст изменить на инструкцию вида: "webRunes Chess started! Please send tweet '#chess @opponent' to invite him/her to play with you."
После чего оппонент должен получить уведомление:
"@username has invited you to play chess. Click URL above to accept"
Текстом (т.е. вне картинки) отображать ссылку, перейдя по которой пользователь дает разрешение chess game app на использование его аккаунта для отсылки твитов-ходов.
После перехода по ссылке и передачи доступа к аккаунту отсылать пригласившему "@opponent accepted your invitation". И отображать картинкой поле 
![image](https://cloud.githubusercontent.com/assets/604410/5576672/8fae085e-9026-11e4-95c8-f5a2efacd704.png)

**Comment by egorzalenski** [comment]
у меня https://github.com/webRunes/Titter-WRIO-App не работает
я ввожу в форму текст нажимаю Send, и открывается чистый экран, без картинки

**Comment by egorzalenski** [comment]
close #4
