### ISSUE TITLE
#chess start. Reward 30 USD

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Chess-WRIO-Game#4]
Подготовить первый pull request после которого должно заработать приложение и его реакция на твиты "#chess start". Конфиг файл пока может быть прямо в проекте с открытыми ключами, после мы перенесем конфиг на сервер, удалим из репозитория и сменим ключи доступа.
Related: https://github.com/webRunes/Chess-WRIO-Game/issues/3

Для примера можно посмотреть как работает https://github.com/webRunes/Login-WRIO-App, см. историю пулл реквестов, где конфиг файл еще был в репозитории.

**Comment by AlexeyAnshakov** [comment]
@egorzalenski , пожалуйста, закройте задачу, оплата за нее ушла.

**Comment by egorzalenski** [comment]
closed #4

**Comment by egorzalenski** [comment]
Closed #4.

**Comment by egorzalenski** [comment]
@AlexeyAnshakov, а как закрыть?

**Comment by AlexeyAnshakov** [comment]
завершить задачу
>Убрать ограничение на точность фразы, т.е. если я введу "бла-бла-бла start #chess", то все равно должен получить "Game started"

**Comment by AM-NiceDay** [comment]
Насколько неточной должна быть фраза? Какие из следующих будут начинать игру?
1) "bla-bla-bla #chess start bla-bla-bla"
2) "bla-bla-bla start #chess bla-bla-bla"
3) "bla-bla-bla start bla-bla-bla #chess"

При работающем третьем варианте поймал один твит, так что думаю, что это слишком свободная формулировка.

**Comment by AlexeyAnshakov** [comment]
В таком случае пусть будет не важна лишь последовательность слов
>start #chess
или
>#chess start
в остальном случае команда не будет проходить.
