### ISSUE TITLE
#chess end issue

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Chess-WRIO-Game#84]
Неправильно отрабатывается команда
>#chess end

в случае отправки ее не в свой ход, пишется, что оппонент сдался, хотя команда была отправлена не им.

**Comment by AlexeyAnshakov** [comment]
Ready for review

**Comment by AlexeyAnshakov** [comment]
По-прежнему неправильно отрабатывает
https://twitter.com/LMorgan72/status/672780871867437056
но 
https://twitter.com/LMorgan72/status/672781027845238785
Чтобы был унифицирован твит, пусть будет
>I give up. @name1, you win!

**Comment by balthazzar** [comment]
так всё нормально же вроде, оппоненту отправлен твит о  том вы сдались.

**Comment by AlexeyAnshakov** [comment]
Нужно поменять текст, чтобы логично было
